package com.yj.weather.pojo;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.ToString;

@ToString
public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.location_id
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    @JSONField(name = "id")
    private String locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.location
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    @JSONField(name = "name")
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.adm
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    @JSONField(name = "adm1")
    private String adm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.lat
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.lon
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    private Double lon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.location_id
     *
     * @return the value of city.location_id
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.location_id
     *
     * @param locationId the value for city.location_id
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId == null ? null : locationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.location
     *
     * @return the value of city.location
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.location
     *
     * @param location the value for city.location
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.adm
     *
     * @return the value of city.adm
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public String getAdm() {
        return adm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.adm
     *
     * @param adm the value for city.adm
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public void setAdm(String adm) {
        this.adm = adm == null ? null : adm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.lat
     *
     * @return the value of city.lat
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.lat
     *
     * @param lat the value for city.lat
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.lon
     *
     * @return the value of city.lon
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.lon
     *
     * @param lon the value for city.lon
     *
     * @mbggenerated Thu Jan 12 11:56:45 CST 2023
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    public String showCity() {
        return adm+location+" "+lon+"E,"+lat+"N";
    }
}