package com.yj.weather.pojo;

import java.util.Date;

public class Weather implements Comparable{
    private static final String[] dayToString= {"今天", "明天", "后天"};
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.location_id
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private String locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.day_of_data
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private Integer dayOfData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.location
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.fx_date
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private Date fxDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.temp_max
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private Double tempMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.temp_min
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private Double tempMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.text_day
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    private String textDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.location_id
     *
     * @return the value of weather.location_id
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.location_id
     *
     * @param locationId the value for weather.location_id
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId == null ? null : locationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.day_of_data
     *
     * @return the value of weather.day_of_data
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public Integer getDayOfData() {
        return dayOfData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.day_of_data
     *
     * @param dayOfData the value for weather.day_of_data
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setDayOfData(Integer dayOfData) {
        this.dayOfData = dayOfData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.location
     *
     * @return the value of weather.location
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.location
     *
     * @param location the value for weather.location
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.fx_date
     *
     * @return the value of weather.fx_date
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public Date getFxDate() {
        return fxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.fx_date
     *
     * @param fxDate the value for weather.fx_date
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setFxDate(Date fxDate) {
        this.fxDate = fxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.temp_max
     *
     * @return the value of weather.temp_max
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public Double getTempMax() {
        return tempMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.temp_max
     *
     * @param tempMax the value for weather.temp_max
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setTempMax(Double tempMax) {
        this.tempMax = tempMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.temp_min
     *
     * @return the value of weather.temp_min
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public Double getTempMin() {
        return tempMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.temp_min
     *
     * @param tempMin the value for weather.temp_min
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setTempMin(Double tempMin) {
        this.tempMin = tempMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.text_day
     *
     * @return the value of weather.text_day
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public String getTextDay() {
        return textDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.text_day
     *
     * @param textDay the value for weather.text_day
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    public void setTextDay(String textDay) {
        this.textDay = textDay == null ? null : textDay.trim();
    }

    public String showWeather() {
        return location + dayToString[dayOfData] + "天气情况: "+textDay +" "+ tempMin + "℃~" + tempMax+"℃";
    }

    @Override
    public int compareTo(Object o) {
        Weather other = (Weather) o;
        if(locationId.equals(other.location)) return dayOfData - other.dayOfData; //升序排序
        else return locationId.compareTo(other.locationId);
    }
}