package com.yj.weather.mapper;

import com.yj.weather.pojo.Weather;
import com.yj.weather.pojo.WeatherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int countByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int deleteByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int deleteByPrimaryKey(@Param("locationId") String locationId, @Param("dayOfData") Integer dayOfData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int insert(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int insertSelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    List<Weather> selectByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    Weather selectByPrimaryKey(@Param("locationId") String locationId, @Param("dayOfData") Integer dayOfData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int updateByExampleSelective(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int updateByExample(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int updateByPrimaryKeySelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated Thu Jan 12 23:48:48 CST 2023
     */
    int updateByPrimaryKey(Weather record);
}